name: lms
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.1.2
  flutter_dotenv: ^5.1.0
  go_router: ^15.1.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  flutter_riverpod: ^2.6.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.0.0
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  visibility_detector: ^0.4.0+2
  video_player: ^2.9.2
  chewie: ^1.8.5
  path_provider: ^2.1.5
  audio_waveforms: ^1.1.1
  just_audio: ^0.10.2
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.4.0
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.6.1
  cached_network_image: ^3.4.1
  syncfusion_flutter_pdfviewer: ^29.1.40
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  socket_io_client: ^3.0.2
  skeletonizer: ^1.4.2
  tuple: ^2.0.2
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  dotted_border: ^2.1.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^19.1.0
  app_settings: ^6.1.1
  intl_utils: ^2.8.7
  animated_toggle_switch: ^0.8.3
  record: ^6.0.0
  device_preview: ^1.2.0
  youtube_player_flutter: ^9.1.1
  flutter_widget_from_html_core: ^0.16.0
  url_launcher: ^6.3.1
  open_file: ^3.5.10
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.2
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^7.0.1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.3
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  flutter_gen_runner:
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  rename: ^3.0.2
  # analyzer: ^6.7.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/pngs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_intl:
  enabled: true
