// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfOEamisi7FBKEkcc4BSX3muovFAdiK9E',
    appId: '1:567860198358:android:364b7612d6064c2aac8277',
    messagingSenderId: '567860198358',
    projectId: 'pradana-lms',
    storageBucket: 'pradana-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyi22pIK4p9UiA4z9MkH9pqU8HT1fE7Qc',
    appId: '1:567860198358:ios:7696676ce6dd99dbac8277',
    messagingSenderId: '567860198358',
    projectId: 'pradana-lms',
    storageBucket: 'pradana-lms.firebasestorage.app',
    iosBundleId: 'com.lms.demo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDil1PJ5pt0y0Anm5uF1AMMyohFmaLZ-Us',
    appId: '1:567860198358:web:f5bff5a283bd339bac8277',
    messagingSenderId: '567860198358',
    projectId: 'pradana-lms',
    authDomain: 'pradana-lms.firebaseapp.com',
    storageBucket: 'pradana-lms.firebasestorage.app',
    measurementId: 'G-1XXKHHK8QK',
  );

}